{
 "title": "PELLIT - Speedtest",
 "time": { "from": "2021-07-26T14:06:27.517Z", "to": "2021-07-26T20:06:27.517Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Descarga",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Carga AS \"time\",\n  Descarga\nFROM medicion\nORDER BY Carga"
    }
   ]
  },
  {
   "title": "Carga",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Carga AS \"time\",\n  Carga\nFROM medicion\nORDER BY Carga"
    }
   ]
  },
  {
   "title": "Latencia [ms]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  Fecha AS \"time\",\n  Latencia\nFROM medicion\nORDER BY Fecha"
    }
   ]
  },
  {
   "title": "Latencia de conexión [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  Fecha AS \"time\",\n  github,\n  google,\n  SERVER\nFROM medicion\nORDER BY Fecha"
    }
   ]
  }
 ]
}